### ISSUE TITLE
Missing trailing comma for omitted return value

### ISSUE THREAD

**Issue by Honour-d-dev** [alchemyplatform/light-account#16]
noticed a missing comma in line 282, tryRecover() returns 3 arguments 
![image](https://github.com/alchemyplatform/light-account/assets/133224432/dca99333-a2b5-4a0a-8fc7-165ea454eb97)
this is in LightAccount.sol btw

**Comment by howydev** [comment]
hi, thank you for your report. this is not the version of `OZ.ECDSA` that we are using

In lib/openzeppelin, it links to this version: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fd81a96f01cc42ef1c9a5399364968d0e07e9e90/contracts/utils/cryptography/ECDSA.sol
