### ISSUE TITLE
Outdated warning in `CustomSlotInitializable`

### ISSUE THREAD

**Issue by HickupHH3** [alchemyplatform/light-account#21]
Due to a change in variable type of `initialized` from `uint8` to `uint64`, the [following warning](https://github.com/alchemyplatform/light-account/blob/main/src/CustomSlotInitializable.sol#L145) is outdated:
```
WARNING: setting the version to 255 will prevent any future reinitialization.
```

Recommendation:
```diff
- WARNING: setting the version to 255 will prevent any future reinitialization.
+ WARNING: setting the version to type(uint64).max will prevent any future reinitialization.
```

**Comment by jaypaik** [comment]
Thanks, good eye!
